language: node_js
node_js:
 - "stable"
addons:
  code_climate:
    repo_token: 5c287eb23c3580a468276a329478962ae9724232
cache:
  directories:
    - "node_modules"
script:
  - npm test
before_script:
  - npm install codeclimate-test-reporter istanbul -g
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
after_script:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info