language: node_js
node_js:
 - "stable"
addons:
  code_climate:
    repo_token: 48b175c3c2f0f332efeccccff7fc7188ea7993760d139d79725edcc7d21d7bbb
cache:
  directories:
    - "node_modules"
script:
  - npm test
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info